import traceback
import webbrowser
from pathlib import Path
from urllib.parse import urlparse

from kivy.utils import platform

from app.core.downloader import get_download_dir


COMMON_COOKIE_URLS = (
    "https://www.tiktok.com",
    "https://m.tiktok.com",
    "https://www.youtube.com",
    "https://accounts.google.com",
    "https://www.facebook.com",
    "https://m.facebook.com",
    "https://www.instagram.com",
    "https://x.com",
    "https://twitter.com",
)

_ANDROID_REFS = []


def default_cookie_file() -> Path:
    return get_download_dir() / "cookies.txt"


def _cookie_domain_for(hostname: str) -> str:
    host = (hostname or "").lower().strip(".")
    if not host:
        return ""
    parts = host.split(".")
    if len(parts) >= 2:
        return "." + ".".join(parts[-2:])
    return host


def _cookies_to_netscape(cookie_rows: list[tuple[str, str]]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by AntiDown WebView login",
    ]
    seen = set()

    for url, cookie_header in cookie_rows:
        host = urlparse(url).hostname or ""
        domain = _cookie_domain_for(host)
        if not domain or not cookie_header:
            continue
        for item in cookie_header.split(";"):
            item = item.strip()
            if not item or "=" not in item:
                continue
            name, value = item.split("=", 1)
            name = name.strip()
            if not name:
                continue
            key = (domain, name)
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"{domain}\tTRUE\t/\tTRUE\t0\t{name}\t{value}")

    return "\n".join(lines) + "\n"


def open_cookie_webview(start_url: str, logger=None, cookie_urls=None) -> bool:
    logger = logger or (lambda message: None)
    if platform != "android":
        webbrowser.open(start_url)
        logger(f"Opened browser login: {start_url}")
        return True

    cookie_urls = tuple(dict.fromkeys((start_url, *(cookie_urls or COMMON_COOKIE_URLS))))
    output_path = default_cookie_file()

    try:
        from android.runnable import run_on_ui_thread
        from jnius import PythonJavaClass, autoclass, java_method

        PythonActivity = autoclass("org.kivy.android.PythonActivity")
        LinearLayout = autoclass("android.widget.LinearLayout")
        LinearLayoutParams = autoclass("android.widget.LinearLayout$LayoutParams")
        ViewGroupLayoutParams = autoclass("android.view.ViewGroup$LayoutParams")
        Button = autoclass("android.widget.Button")
        WebView = autoclass("android.webkit.WebView")
        WebViewClient = autoclass("android.webkit.WebViewClient")
        CookieManager = autoclass("android.webkit.CookieManager")
        Color = autoclass("android.graphics.Color")
    except Exception as exc:
        logger(f"Could not prepare Android WebView login: {exc}")
        logger(traceback.format_exc())
        return False

    class ClickListener(PythonJavaClass):
        __javainterfaces__ = ["android/view/View$OnClickListener"]
        __javacontext__ = "app"

        def __init__(self, callback):
            super().__init__()
            self.callback = callback

        @java_method("(Landroid/view/View;)V")
        def onClick(self, _view):
            self.callback()

    @run_on_ui_thread
    def show_webview():
        try:
            activity = PythonActivity.mActivity
            cookie_manager = CookieManager.getInstance()
            cookie_manager.setAcceptCookie(True)

            layout = LinearLayout(activity)
            layout.setOrientation(LinearLayout.VERTICAL)
            layout.setBackgroundColor(Color.WHITE)

            toolbar = LinearLayout(activity)
            toolbar.setOrientation(LinearLayout.HORIZONTAL)

            save_button = Button(activity)
            save_button.setText("Save Cookies & Close")
            close_button = Button(activity)
            close_button.setText("Close")

            webview = WebView(activity)
            settings = webview.getSettings()
            settings.setJavaScriptEnabled(True)
            settings.setDomStorageEnabled(True)
            settings.setDatabaseEnabled(True)
            settings.setLoadWithOverviewMode(True)
            settings.setUseWideViewPort(True)
            webview.setWebViewClient(WebViewClient())
            try:
                cookie_manager.setAcceptThirdPartyCookies(webview, True)
            except Exception:
                pass

            def close():
                try:
                    webview.stopLoading()
                    parent = layout.getParent()
                    if parent:
                        parent.removeView(layout)
                    webview.destroy()
                finally:
                    _ANDROID_REFS.clear()

            def save_and_close():
                cookie_manager.flush()
                rows = []
                for url in cookie_urls:
                    cookie_header = cookie_manager.getCookie(url)
                    if cookie_header:
                        rows.append((url, cookie_header))
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(_cookies_to_netscape(rows), encoding="utf-8")
                logger(f"Saved cookies to: {output_path}")
                close()

            save_listener = ClickListener(save_and_close)
            close_listener = ClickListener(close)
            _ANDROID_REFS[:] = [layout, toolbar, save_button, close_button, webview, save_listener, close_listener]

            save_button.setOnClickListener(save_listener)
            close_button.setOnClickListener(close_listener)

            toolbar.addView(save_button, LinearLayoutParams(0, LinearLayoutParams.WRAP_CONTENT, 1.0))
            toolbar.addView(close_button, LinearLayoutParams(0, LinearLayoutParams.WRAP_CONTENT, 1.0))
            layout.addView(toolbar, LinearLayoutParams(LinearLayoutParams.MATCH_PARENT, LinearLayoutParams.WRAP_CONTENT))
            layout.addView(webview, LinearLayoutParams(LinearLayoutParams.MATCH_PARENT, 0, 1.0))
            activity.addContentView(
                layout,
                ViewGroupLayoutParams(ViewGroupLayoutParams.MATCH_PARENT, ViewGroupLayoutParams.MATCH_PARENT),
            )
            webview.loadUrl(start_url)
        except Exception as exc:
            logger(f"Could not open Android WebView login: {exc}")
            logger(traceback.format_exc())

    show_webview()
    logger(f"Opened WebView login: {start_url}")
    return True
